import Link from "next/link";
import { asc, count, desc, eq, sql } from "drizzle-orm";
import { db } from "@/db";
import { attempts, classes, documents, exams, questions, user } from "@/db/schema";
import { Card, Input } from "@/components/ui";
import { UserActions } from "@/components/user-actions";
import { DocumentUpload } from "@/components/document-upload";
import { createClass, importExam, renameClass, setExamStatus, toggleClassArchive } from "@/lib/actions";
import { requireAdmin } from "@/lib/session";

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ csvErrors?: string }> }) {
  await requireAdmin(); const query = await searchParams;
  const classRows = await db.select({ id: classes.id, name: classes.name, archivedAt: classes.archivedAt, documents: count(documents.id) }).from(classes).leftJoin(documents, eq(documents.classId, classes.id)).groupBy(classes.id).orderBy(asc(classes.name));
  const examRows = await db.select({ id: exams.id, title: exams.title, classId: exams.classId, status: exams.status, questions: count(questions.id) }).from(exams).leftJoin(questions, eq(questions.examId, exams.id)).groupBy(exams.id).orderBy(desc(exams.createdAt));
  const users = await db.select().from(user).orderBy(asc(user.username));
  const recent = await db.select({ id: attempts.id, username: user.username, exam: exams.title, attemptNumber: attempts.attemptNumber, score: attempts.score, percentage: attempts.percentage, submittedAt: attempts.submittedAt }).from(attempts).innerJoin(user, eq(attempts.userId, user.id)).innerJoin(exams, eq(attempts.examId, exams.id)).where(eq(attempts.status, "submitted")).orderBy(desc(attempts.submittedAt)).limit(50);
  const used = await db.select({ bytes: sql<number>`coalesce(sum(${documents.size}), 0)` }).from(documents);
  return <main className="shell stack"><div className="row between"><div><h1>Admin</h1><p className="muted">{classRows.length} classes · {(Number(used[0].bytes) / 1024 / 1024).toFixed(1)} / 750 MB PDFs</p></div><Link className="button secondary" href="/admin/analytics">Analytics</Link></div>
    {query.csvErrors && <Card><h2 className="danger">CSV errors</h2><ul>{query.csvErrors.split("|").map((error) => <li key={error}>{error}</li>)}</ul></Card>}
    <Card><h2>Classes</h2><form className="row" action={createClass}><Input name="name" placeholder="New class name" required /><button className="button">Create</button></form><div className="table-wrap"><table><thead><tr><th>Class</th><th>PDFs</th><th>Manage</th></tr></thead><tbody>{classRows.map((item) => <tr key={item.id}><td><form className="row" action={renameClass}><input type="hidden" name="id" value={item.id} /><Input name="name" defaultValue={item.name} required /><button className="button secondary small">Rename</button></form></td><td>{item.documents}</td><td><form action={toggleClassArchive}><input type="hidden" name="id" value={item.id} /><button className={`button small ${item.archivedAt ? "secondary" : "danger-button"}`}>{item.archivedAt ? "Restore" : "Archive"}</button></form></td></tr>)}</tbody></table></div></Card>
    <Card><h2>Upload private PDF</h2><DocumentUpload classes={classRows.filter((item) => !item.archivedAt).map(({ id, name }) => ({ id, name }))} /></Card>
    <Card><h2>Import draft exam</h2><p className="muted">Exact columns: question, option_a–d, correct_answer, explanation. Maximum 100 rows.</p><form className="grid" action={importExam}><select className="input" name="classId" required>{classRows.filter((item) => !item.archivedAt).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><Input name="title" placeholder="Exam title" required /><Input name="file" type="file" accept="text/csv,.csv" required /><button className="button">Import and preview</button></form></Card>
    <Card><h2>Exams</h2><div className="table-wrap"><table><thead><tr><th>Exam</th><th>Status</th><th>Questions</th><th>Actions</th></tr></thead><tbody>{examRows.map((exam) => <tr key={exam.id}><td>{exam.title}</td><td><span className="pill">{exam.status}</span></td><td>{exam.questions}</td><td><div className="row"><Link className="button secondary small" href={`/admin/exams/${exam.id}`}>Preview</Link><a className="button secondary small" href={`/api/exams/${exam.id}/source`}>CSV</a>{exam.status !== "archived" && <><form action={setExamStatus}><input type="hidden" name="id" value={exam.id} /><input type="hidden" name="status" value={exam.status === "published" ? "draft" : "published"} /><button className="button small">{exam.status === "published" ? "Unpublish" : "Publish"}</button></form><form action={setExamStatus}><input type="hidden" name="id" value={exam.id} /><input type="hidden" name="status" value="archived" /><button className="button danger-button small">Archive</button></form></>}</div></td></tr>)}</tbody></table></div></Card>
    <Card><h2>Students</h2><div className="table-wrap"><table><thead><tr><th>Username</th><th>Status</th><th>Temporary password</th></tr></thead><tbody>{users.filter((item) => item.role !== "admin").map((item) => <tr key={item.id}><td>{item.username}</td><td>{item.banned ? "Deactivated" : item.mustChangePassword ? "Password change required" : "Active"}</td><td><UserActions userId={item.id} banned={item.banned} /></td></tr>)}</tbody></table></div></Card>
    <Card><h2>Submitted attempts</h2><div className="table-wrap"><table><thead><tr><th>Username</th><th>Exam</th><th>Attempt</th><th>Score</th><th>Submitted</th></tr></thead><tbody>{recent.map((item) => <tr key={item.id}><td>{item.username}</td><td>{item.exam}</td><td>{item.attemptNumber}</td><td><Link className="success" href={`/admin/attempts/${item.id}`}>{item.score} · {item.percentage}%</Link></td><td>{item.submittedAt?.toLocaleString()}</td></tr>)}</tbody></table></div></Card>
  </main>;
}
